"""cache_operations_split - Split cache operations module

This module was split from cache_operations.py (1213 lines) for better maintainability.

Split into modules:
- models: Gateway imports and utilities
- lugs_operations: LUGSIntegratedCacheOperations class
- standalone_functions: _get_cache_instance singleton
- cache_functions: cache_* standalone functions
- adapters: Adapter functions for wrappers
- stampede_protection: Stampede protection implementations

All exports are re-exported for backward compatibility.
"""

from __future__ import annotations

from lee.lee_cache.cache_operations_split.lugs_operations import (
    LUGSIntegratedCacheOperations,
)
from lee.lee_cache.cache_operations_split.standalone_functions import (
    _get_cache_instance,
)
from lee.lee_cache.cache_operations_split.cache_functions import (
    cache_get,
    cache_set,
    cache_exists,
    cache_delete,
    cache_clear,
    cache_reset,
    cache_cleanup_expired,
    cache_get_stats,
    cache_get_metadata,
    cache_get_module_dependencies,
    cache_keys,
    cache_values,
    cache_items,
    cache_pop,
    cache_update,
    cache_touch,
    cache_increment,
    cache_get_many,
    cache_set_many,
)
from lee.lee_cache.cache_operations_split.adapters import (
    _cache_adapter,
    _execute_get_implementation,
    _execute_set_implementation,
    _execute_exists_implementation,
    _execute_delete_implementation,
    _execute_clear_implementation,
    _execute_get_stats_implementation,
    _execute_reset_implementation,
    _execute_cleanup_expired_implementation,
    _execute_get_metadata_implementation,
    _execute_get_module_dependencies_implementation,
    _execute_keys_implementation,
    _execute_values_implementation,
    _execute_items_implementation,
    _execute_pop_implementation,
    _execute_update_implementation,
    _execute_touch_implementation,
    _execute_increment_implementation,
)
from lee.lee_cache.cache_operations_split.stampede_protection import (
    _execute_get_with_grace_period_implementation,
    _execute_get_or_compute_implementation,
    _execute_process_pending_refreshes_implementation,
)

__all__ = [
    # Class-based operations
    "LUGSIntegratedCacheOperations",
    "_get_cache_instance",

    # Standalone functions
    "cache_get",
    "cache_set",
    "cache_exists",
    "cache_delete",
    "cache_clear",
    "cache_reset",
    "cache_cleanup_expired",
    "cache_get_stats",
    "cache_get_metadata",
    "cache_get_module_dependencies",
    "cache_keys",
    "cache_values",
    "cache_items",
    "cache_pop",
    "cache_update",
    "cache_touch",
    "cache_increment",
    "cache_get_many",
    "cache_set_many",

    # Generic Adapter Decorator
    "_cache_adapter",

    # Adapter Functions for Wrappers (generated by _cache_adapter)
    "_execute_get_implementation",
    "_execute_set_implementation",
    "_execute_exists_implementation",
    "_execute_delete_implementation",
    "_execute_clear_implementation",
    "_execute_get_stats_implementation",
    "_execute_reset_implementation",
    "_execute_cleanup_expired_implementation",
    "_execute_get_metadata_implementation",
    "_execute_get_module_dependencies_implementation",
    "_execute_keys_implementation",
    "_execute_values_implementation",
    "_execute_items_implementation",
    "_execute_pop_implementation",
    "_execute_update_implementation",
    "_execute_touch_implementation",
    "_execute_increment_implementation",

    # Phase 1: Stampede Protection & Stale-While-Revalidate
    "_execute_get_with_grace_period_implementation",
    "_execute_get_or_compute_implementation",
    "_execute_process_pending_refreshes_implementation",
]
